CC=g++
CFLAGS=-g -Wall -Werror
FILES=Rectangle.cpp TestRect.cpp program.cpp

default:
	@echo "-- Compiling executable --"
	$(CC) $(CFLAGS) $(FILES) -o program

clean:
	@echo "-- Deleting executable --"
	rm program