#!/bin/bash

#   Author: 			        Tor Hagen
#   Class:	       		    CS160B
#   Date:   	       		  Mon Nov. 23 2015
#   Instructor:	    		  Peter Wood
#   NoF:        	   			prompt2
#		Inputs/Args: 	 
#													
#		Outputs:
#

# First we set up some variables to hold information about our state (if we're to keep asking questions or not)
# and an array to hold our inputs. We also declare the name of our logging file here
keepgoing=true
musicarray=()
logfile="log.prompt2.txt"

# Colors 
RED='\033[0;31m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
ORANGE='\033[0;33m'
NC='\033[0m'

# If the logfile exists but we can't write to it, error and exit as 
# something is wrong
if [[ -e "$logfile" ]] && ! [[ -w "$logfile" ]] ; 
then
	echo -e "ERROR: Logfile for program exists but can't write to it!"
	exit 1
fi

# if the logfile doesn't exist we have to make it somehow, touch 
# takes care of that for us 
if ! [[ -e "$logfile" ]] ; 
then
	touch "$logfile"
fi

# Once we make sure that the logfile can be written to we write some log entries indicating
# that the program started, when it started and who ran it on the system
echo -e "`date -I`||`date +%T`||'`whoami`'\t ** Script started **\t`date`" >> "$logfile"
echo -e "`date -I`||`date +%T`||'`whoami`'\t ** By user **\t`whoami`" >> "$logfile"
echo -e "`date -I`||`date +%T`||'`whoami`'\t ** Starting session log **" >> "$logfile"

# Here we just keep rocking until we decide at some point to change $keepgoing to false
while [[ "$keepgoing" = true ]] ; 
do

	# Then we present the user with the choices 
	# and read it in, then log that choice to the $logfile using >> to append
	echo -e "What kind of music do you listen to?"
	echo -e "(folk, electronic, blues, jazz, classical, rock or ${RED}quit${NC})"
	read choice
	echo -e "`date -I`||`date +%T`||'`whoami`'\t -- user raw input: $choice" >> "$logfile"

	# Then we handle the user choice with a case list as here 
	# Each input will be logged once to the musicarray, and also >> appended to the logfile
	case $choice in

		"folk"|"f" )
			echo -e "${BLUE}How many folk singers does it take to change a light bulb?${NC}\n${GREEN}Three. One to change it and two to sing about how great the old one was.${NC}"
			echo
			musicarray=("${musicarray[*]}"$choice" ")
			echo -e "`date -I`||`date +%T`||'`whoami`'\t ++ which maps to 'folk'" >> "$logfile"
			;;

		"electronic"|"e" )
			echo -e "${ORANGE}It used to be called modem noise, now it's called Skrillex.${NC}"
			echo
			musicarray=("${musicarray[*]}"$choice" ")
			echo -e "`date -I`||`date +%T`||'`whoami`'\t ++ which maps to 'electronic'" >> "$logfile"
			;;

		"blues"|"b" )
			echo -e "${BLUE}If it doesn't open with 'I woke up this morning...', start over...${NC}"
			echo
			musicarray=("${musicarray[*]}"$choice" ")
			echo -e "`date -I`||`date +%T`||'`whoami`'\t ++ which maps to 'blues'" >> "$logfile"
			;;

		"jazz"|"j" )
			echo -e "${CYAN}How does a Jazz musician end up with a million dollars?${NC}\n${GREEN}By starting out with two million dollars.${NC}"
			echo
			musicarray=("${musicarray[*]}"$choice" ")
			echo -e "`date -I`||`date +%T`||'`whoami`'\t ++ which maps to 'jazz'" >> "$logfile"
			;;

		"classical"|"c" )
			echo -e "${BLUE}Why couldn't the string quartet find their composer?${NC}\n${GREEN}He was Haydn.${NC}"
			echo
			musicarray=("${musicarray[*]}"$choice" ")
			echo -e "`date -I`||`date +%T`||'`whoami`'\t ++ which maps to 'classical'" >> "$logfile"
			;;

		"rock"|"r" )
			echo -e "${CYAN}What does a lead guitarist use for contraception?${NC}\n${GREEN}His personality.${NC}"
			echo
			musicarray=("${musicarray[*]}"$choice" ")
			echo -e "`date -I`||`date +%T`||'`whoami`'\t ++ which maps to 'rock'" >> "$logfile"
			;;

		# if this option is selected in the case we flip our boolean switch to false and end it here
		# making sure to log that as well
		"quit"|"q" )
			echo -e "OK quitting."
			echo -e "`date -I`||`date +%T`||'`whoami`'\t ** Script ended **\t`date`" >> "$logfile"
			keepgoing=false
			;;
	esac

done

# Then we simply output the matches the user did while the program ran (not log)
echo -e "You matched the following words while the program ran:"
echo -e "${musicarray[*]}"